import type { Player, Game, Version, CharacterId } from '@/lib/types'



// ─── PLAYERS ────────────────────────────────────────────────────────────────
// Add/edit players here
export const PLAYERS: Player[] = [
  { id: 'austin', name: 'Austin' },
  { id: 'josh', name: 'Josh' },
  { id: 'justin', name: 'Justin' },
  { id: 'tom', name: 'Tom' },
  { id: 'chris', name: 'Chris' },
  { id: 'dario', name: 'Dario' },
  { id: 'eddie', name: 'Eddie' },
  { id: 'everett', name: 'Everett' },
]

// ─── CHARACTER ORDER ─────────────────────────────────────────────────────────
// Same order as the how-to-play / character guide page
export const CHARACTER_ORDER: CharacterId[] = [
  'donkey-kong',
  'diddy-kong',
  'dixie-kong',
  'kiddy-kong',
  'tiny-kong',
  'lanky-kong',
  'chunky-kong',
  'taj',
  'xananab',
  'klubba',
  'voidco',
  'king-k-rool',
]

export const CHARACTER_NAMES: Record<CharacterId, string> = {
  'donkey-kong': 'Donkey Kong',
  'diddy-kong': 'Diddy Kong',
  'dixie-kong': 'Dixie Kong',
  'kiddy-kong': 'Kiddy Kong',
  'tiny-kong': 'Tiny Kong',
  'lanky-kong': 'Lanky Kong',
  'chunky-kong': 'Chunky Kong',
  'taj': 'Taj',
  'xananab': 'Xananab',
  'klubba': 'Klubba',
  'voidco': 'VoidCo',
  'king-k-rool': 'King K. Rool',
}

// ─── VERSIONS ────────────────────────────────────────────────────────────────
export const VERSIONS: Version[] = [
  {
    id: 'v1.0',
    displayName: 'v1.0',
    date: '2022-01-01',
    summary: '',
    highlights: [],
    statsSchema: [
      {
        key: 'levelsBuilt',
        label: 'Levels Built',
        type: 'number',
      },
      {
        key: 'turnsTaken',
        label: 'Turns Taken',
        type: 'number',
      },
      {
        key: 'bangCompleted',
        label: '! Completed',
        type: 'number',
      },
    ],
  },
  {
    id: 'v1.1',
    displayName: 'v1.1',
    date: '2022-03-01',
    summary: '',
    highlights: [],
    statsSchema: [
      {
        key: 'levelsBuilt',
        label: 'Levels Built',
        type: 'number',
      },
      {
        key: 'turnsTaken',
        label: 'Turns Taken',
        type: 'number',
      },
      {
        key: 'bangCompleted',
        label: '! Completed',
        type: 'number',
      },
    ],
  },
  {
    id: 'v2.0',
    displayName: 'v2.0',
    date: '2022-07-01',
    summary: '',
    highlights: [],
    statsSchema: [
      {
        key: 'levelsBuilt',
        label: 'Levels Built',
        type: 'number',
      },
      {
        key: 'turnsTaken',
        label: 'Turns Taken',
        type: 'number',
      },
      {
        key: 'bangCompleted',
        label: '! Completed',
        type: 'number',
      },
    ],
  },
  {
    id: 'v3.0',
    displayName: 'v3.0',
    date: '2023-01-01',
    summary: '',
    highlights: [],
    statsSchema: [
      {
        key: 'levelsBuilt',
        label: 'Levels Built',
        type: 'number',
      },
      {
        key: 'turnsTaken',
        label: 'Turns Taken',
        type: 'number',
      },
      {
        key: 'bangCompleted',
        label: '! Completed',
        type: 'number',
      },
    ],
  },
  {
    id: 'v3.1',
    displayName: 'v3.1',
    date: '2023-04-01',
    summary: '',
    highlights: [],
    statsSchema: [
      {
        key: 'levelsBuilt',
        label: 'Levels Built',
        type: 'number',
      },
      {
        key: 'turnsTaken',
        label: 'Turns Taken',
        type: 'number',
      },
      {
        key: 'bangCompleted',
        label: '! Completed',
        type: 'number',
      },
    ],
  },
  {
    id: 'v4.2',
    displayName: 'v4.2',
    date: '2023-08-01',
    summary: '',
    highlights: [],
    statsSchema: [
      {
        key: 'levelsBuilt',
        label: 'Levels Built',
        type: 'number',
      },
      {
        key: 'turnsTaken',
        label: 'Turns Taken',
        type: 'number',
      },
      {
        key: 'bangCompleted',
        label: '! Completed',
        type: 'number',
      },
    ],
  },
  {
    id: 'v4.3',
    displayName: 'v4.3',
    date: '2023-11-01',
    summary: '',
    highlights: [],
    statsSchema: [
      {
        key: 'levelsBuilt',
        label: 'Levels Built',
        type: 'number',
      },
      {
        key: 'turnsTaken',
        label: 'Turns Taken',
        type: 'number',
      },
      {
        key: 'bangCompleted',
        label: '! Completed',
        type: 'number',
      },
    ],
  },

{
  id: 'v5.0',
  displayName: 'v5.0',
  date: '2024-01-01',
  summary: '',
  highlights: [],
  statsSchema: [
    {
      key: 'turnsTaken',
      label: 'Turns Taken',
      type: 'number',
    },
    {
      key: 'levelStats',
      label: 'Level Stats',
      type: 'object',
    },
    {
      key: 'scrapbook',
      label: 'Scrapbook',
      type: 'array',
    },
  ],
}
]

// ─── GAMES ───────────────────────────────────────────────────────────────────
export const GAMES: Game[] = [
  // Example game data
  {
  id: '11',
  date: '2024-4-15',
  version: 'v4.3',
  placements: [
    {
      playerId: 'austin',
      teamId: 'team-1',
      characterId: 'dixie-kong',
      place: 2,
      turnsTaken: 512,
      levelStats : {
  "Jungle Hijinxs": { buildOrder: 22, star: 0, bang: 0, save: 0 },
  "Ropey Rampage": { buildOrder: 54, star: 0, bang: 0, save: 0 },
  "Reptile Rumble": { buildOrder: 48, star: 0, bang: 0, save: 0 },
  "Coral Capers": { buildOrder: 36, star: 0, bang: 0, save: 0 },
  "Barrel Cannon Canyon": { buildOrder: 1, star: 0, bang: 0, save: 0 },
  "Very Gnawty's Lair": { buildOrder: 57, star: 0, bang: 0, save: 0 },

  "Winky's Walkway": { buildOrder: 114, star: 0, bang: 0, save: 0 },
  "Mine Cart Carnage": { buildOrder: 55, star: 0, bang: 0, save: 0 },
  "Bouncy Bonanza": { buildOrder: 134, star: 0, bang: 0, save: 0 },
  "Stop & Go Station": { buildOrder: 18, star: 0, bang: 0, save: 0 },
  "Millstone Mayhem": { buildOrder: 51, star: 0, bang: 0, save: 0 },
  "Necky's Nuts": { buildOrder: 29, star: 0, bang: 0, save: 0 },

  "Vulture Culture": { buildOrder: 131, star: 0, bang: 0, save: 0 },
  "Tree Top Town": { buildOrder: 37, star: 0, bang: 0, save: 0 },
  "Forest Frenzy": { buildOrder: 116, star: 0, bang: 0, save: 0 },
  "Orang-Utan Gang": { buildOrder: 93, star: 0, bang: 0, save: 0 },
  "Clam City": { buildOrder: 12, star: 0, bang: 0, save: 0 },
  "Temple Tempest": { buildOrder: 77, star: 0, bang: 0, save: 0 },
  "Bumble B. Rumble": { buildOrder: 44, star: 0, bang: 0, save: 0 },

  "Snow Barrel Blast": { buildOrder: 115, star: 0, bang: 0, save: 0 },
  "Slipslide Ride": { buildOrder: 126, star: 0, bang: 0, save: 0 },
  "Croctopus Chase": { buildOrder: 69, star: 0, bang: 0, save: 0 },
  "Ice Age Alley": { buildOrder: 107, star: 0, bang: 0, save: 0 },
  "Rope Bridge Rumble": { buildOrder: 111, star: 0, bang: 0, save: 0 },
  "Torchlight Trouble": { buildOrder: 141, star: 0, bang: 0, save: 0 },
  "Really Gnawty Rampage": { buildOrder: 53, star: 0, bang: 0, save: 0 },

  "Oil Drum Alley": { buildOrder: 60, star: 0, bang: 0, save: 0 },
  "Trick Track Trek": { buildOrder: 82, star: 0, bang: 0, save: 0 },
  "Poison Pond": { buildOrder: 122, star: 0, bang: 0, save: 0 },
  "Elevator Antics": { buildOrder: 130, star: 0, bang: 0, save: 0 },
  "Blackout Basement": { buildOrder: 118, star: 0, bang: 0, save: 0 },
  "Mine Cart Madness": { buildOrder: 61, star: 0, bang: 0, save: 0 },
  "Boss Dumb Drum": { buildOrder: 5, star: 0, bang: 0, save: 0 },

  "Tanked Up Trouble": { buildOrder: 106, star: 0, bang: 0, save: 0 },
  "Manic Mincers": { buildOrder: 86, star: 0, bang: 0, save: 0 },
  "Misty Mine": { buildOrder: 123, star: 0, bang: 0, save: 0 },
  "Loopy Lights": { buildOrder: 25, star: 0, bang: 0, save: 0 },
  "Platform Perils": { buildOrder: 96, star: 0, bang: 0, save: 0 },
  "Necky's Revenge": { buildOrder: 89, star: 0, bang: 0, save: 0 },

  "Gang-Plank Galleon": { buildOrder: 34, star: 0, bang: 0, save: 0 },

  "Pirate Panic": { buildOrder: 119, star: 0, bang: 0, save: 0 },
  "Mainbrace Mayhem": { buildOrder: 113, star: 0, bang: 0, save: 0 },
  "Gangplank Galley": { buildOrder: 125, star: 0, bang: 0, save: 0 },
  "Lockjaw's Locker": { buildOrder: 35, star: 0, bang: 0, save: 0 },
  "Topsail Trouble": { buildOrder: 117, star: 0, bang: 0, save: 0 },
  "Krow's Nest": { buildOrder: 137, star: 0, bang: 0, save: 0 },

  "Hot-Head Hop": { buildOrder: 19, star: 0, bang: 0, save: 0 },
  "Kannon's Klaim": { buildOrder: 62, star: 0, bang: 0, save: 0 },
  "Lava Lagoon": { buildOrder: 103, star: 0, bang: 0, save: 0 },
  "Red-Hot Ride": { buildOrder: 124, star: 0, bang: 0, save: 0 },
  "Squawks's Shaft": { buildOrder: 88, star: 0, bang: 0, save: 0 },
  "Kleever's Kiln": { buildOrder: 21, star: 0, bang: 0, save: 0 },

  "Barrel Bayou": { buildOrder: 81, star: 0, bang: 0, save: 0 },
  "Glimmer's Galleon": { buildOrder: 129, star: 0, bang: 0, save: 0 },
  "Krockhead Klamber": { buildOrder: 98, star: 0, bang: 0, save: 0 },
  "Rattle Battle": { buildOrder: 78, star: 0, bang: 0, save: 0 },
  "Slime Climb": { buildOrder: 110, star: 0, bang: 0, save: 0 },
  "Bramble Blast": { buildOrder: 16, star: 0, bang: 0, save: 0 },
  "Kudgel's Kontest": { buildOrder: 46, star: 0, bang: 0, save: 0 },

  "Hornet Hole": { buildOrder: 140, star: 0, bang: 0, save: 0 },
  "Target Terror": { buildOrder: 42, star: 0, bang: 0, save: 0 },
  "Bramble Scramble": { buildOrder: 68, star: 0, bang: 0, save: 0 },
  "Rickety Race": { buildOrder: 50, star: 0, bang: 0, save: 0 },
  "Mudhole Marsh": { buildOrder: 59, star: 0, bang: 0, save: 0 },
  "Rambi Rumble": { buildOrder: 45, star: 0, bang: 0, save: 0 },
  "King Zing Sting": { buildOrder: 95, star: 0, bang: 0, save: 0 },

  "Ghostly Grove": { buildOrder: 7, star: 0, bang: 0, save: 0 },
  "Haunted Hall": { buildOrder: 33, star: 0, bang: 0, save: 0 },
  "Gusty Glade": { buildOrder: 32, star: 0, bang: 0, save: 0 },
  "Parrot Chute Panic": { buildOrder: 102, star: 0, bang: 0, save: 0 },
  "Web Woods": { buildOrder: 14, star: 0, bang: 0, save: 0 },
  "Kreepy Krow": { buildOrder: 39, star: 0, bang: 0, save: 0 },

  "Arctic Abyss": { buildOrder: 6, star: 0, bang: 0, save: 0 },
  "Castle Crush": { buildOrder: 24, star: 0, bang: 0, save: 0 },
  "Clapper's Cavern": { buildOrder: 94, star: 0, bang: 0, save: 0 },
  "Windy Well": { buildOrder: 4, star: 0, bang: 0, save: 0 },
  "Chain Link Chamber": { buildOrder: 15, star: 0, bang: 0, save: 0 },
  "Toxic Tower": { buildOrder: 84, star: 0, bang: 0, save: 0 },
  "Stronghold Showdown": { buildOrder: 132, star: 0, bang: 0, save: 0 },

  "Screech's Sprint": { buildOrder: 109, star: 0, bang: 0, save: 0 },
  "K. Rool Duel": { buildOrder: 138, star: 0, bang: 0, save: 0 },

  "Jungle Jinx": { buildOrder: 97, star: 0, bang: 0, save: 0 },
  "Black Ice Battle": { buildOrder: 139, star: 0, bang: 0, save: 0 },
  "Klobber Karnage": { buildOrder: 49, star: 0, bang: 0, save: 0 },
  "Fiery Furnace": { buildOrder: 108, star: 0, bang: 0, save: 0 },
  "Animal Antics": { buildOrder: 47, star: 0, bang: 0, save: 0 },
  "Krocodile Kore": { buildOrder: 66, star: 0, bang: 0, save: 0 },

  "Lakeside Limbo": { buildOrder: 104, star: 0, bang: 0, save: 0 },
  "Doorstop Dash": { buildOrder: 8, star: 0, bang: 0, save: 0 },
  "Tidal Trouble": { buildOrder: 13, star: 0, bang: 0, save: 0 },
  "Skidda's Row": { buildOrder: 121, star: 0, bang: 0, save: 0 },
  "Murky Mill": { buildOrder: 73, star: 0, bang: 0, save: 0 },
  "Belcha's Barn": { buildOrder: 127, star: 0, bang: 0, save: 0 },

  "Springin' Spiders": { buildOrder: 75, star: 0, bang: 0, save: 0 },
  "Riverside Race": { buildOrder: 120, star: 0, bang: 0, save: 0 },
  "Squeals on Wheels": { buildOrder: 135, star: 0, bang: 0, save: 0 },
  "Barrel Shield Bust-Up": { buildOrder: 30, star: 0, bang: 0, save: 0 },
  "Bobbing Barrel Brawl": { buildOrder: 133, star: 0, bang: 0, save: 0 },
  "Arich's Ambush": { buildOrder: 63, star: 0, bang: 0, save: 0 },

  "Bazza's Blockade": { buildOrder: 52, star: 0, bang: 0, save: 0 },
  "Rocket Barrel Ride": { buildOrder: 128, star: 0, bang: 0, save: 0 },
  "Kreeping Klasps": { buildOrder: 2, star: 0, bang: 0, save: 0 },
  "Tracker Barrel Trek": { buildOrder: 58, star: 0, bang: 0, save: 0 },
  "Fish Food Frenzy": { buildOrder: 92, star: 0, bang: 0, save: 0 },
  "Squirt's Showdown": { buildOrder: 3, star: 0, bang: 0, save: 0 },

  "Fire-Ball Frenzy": { buildOrder: 28, star: 0, bang: 0, save: 0 },
  "Demolition Drain-Pipe": { buildOrder: 65, star: 0, bang: 0, save: 0 },
  "Ripsaw Rage": { buildOrder: 9, star: 0, bang: 0, save: 0 },
  "Blazing Bazukas": { buildOrder: 90, star: 0, bang: 0, save: 0 },
  "Low-G Labyrinth": { buildOrder: 87, star: 0, bang: 0, save: 0 },
  "KAOS Karnage": { buildOrder: 80, star: 0, bang: 0, save: 0 },

  "Krevice Kreepers": { buildOrder: 112, star: 0, bang: 0, save: 0 },
  "Tearaway Toboggan": { buildOrder: 23, star: 0, bang: 0, save: 0 },
  "Barrel Drop Bounce": { buildOrder: 43, star: 0, bang: 0, save: 0 },
  "Krack-Shot Kroc": { buildOrder: 64, star: 0, bang: 0, save: 0 },
  "Lemguin Lunge": { buildOrder: 91, star: 0, bang: 0, save: 0 },
  "Bleak's House": { buildOrder: 71, star: 0, bang: 0, save: 0 },

  "Buzzer Barrage": { buildOrder: 105, star: 0, bang: 0, save: 0 },
  "Kong-Fused Cliffs": { buildOrder: 67, star: 0, bang: 0, save: 0 },
  "Floodlit Fish": { buildOrder: 11, star: 0, bang: 0, save: 0 },
  "Pot Hole Panic": { buildOrder: 27, star: 0, bang: 0, save: 0 },
  "Ropey Rumpus": { buildOrder: 142, star: 0, bang: 0, save: 0 },
  "Kroctopus Krush": { buildOrder: 70, star: 0, bang: 0, save: 0 },

  "Dingy Drain-Pipe": { buildOrder: 17, star: 0, bang: 0, save: 0 },
  "Stormy Seas": { buildOrder: 40, star: 0, bang: 0, save: 0 },
  "Sunken Spruce": { buildOrder: 79, star: 0, bang: 0, save: 0 },
  "Cliffside Blast": { buildOrder: 31, star: 0, bang: 0, save: 0 },
  "Ripcurl Reef": { buildOrder: 26, star: 0, bang: 0, save: 0 },
  "Surf's Up": { buildOrder: 41, star: 0, bang: 0, save: 0 },
  "Barbos's Barrier": { buildOrder: 76, star: 0, bang: 0, save: 0 },

  "Konveyor Rope Klash": { buildOrder: 72, star: 0, bang: 0, save: 0 },
  "Creepy Caverns": { buildOrder: 99, star: 0, bang: 0, save: 0 },
  "Lightning Looks-Out": { buildOrder: 85, star: 0, bang: 0, save: 0 },
  "Koindozer Klamber": { buildOrder: 38, star: 0, bang: 0, save: 0 },
  "Poisonous Pipeline": { buildOrder: 20, star: 0, bang: 0, save: 0 },
  "Kastle KAOS": { buildOrder: 101, star: 0, bang: 0, save: 0 },

  "Stampede Sprint": { buildOrder: 136, star: 0, bang: 0, save: 0 },
  "Criss Kross Cliffs": { buildOrder: 10, star: 0, bang: 0, save: 0 },
  "Tyrant Twin Tussle": { buildOrder: 83, star: 0, bang: 0, save: 0 },
  "Swoopy Salvo": { buildOrder: 100, star: 0, bang: 0, save: 0 },
  "Rocket Rush": { buildOrder: 36, star: 0, bang: 0, save: 0 },
  "Knautilus": { buildOrder: 74, star: 0, bang: 0, save: 0 },
},

      scrapbook: [
        "Clapper", "Ellie", "Enguarde", "Expresso", "Glimmer", "Parry",
  "Quawks", "Rambi", "Rattly", "Squawks", "Squitter", "Winky", "Balloons", "Barrel Cannons", "Barrels", "Boss", "Carts", "Chase",
  "Conveyors", "Doors", "Drums", "Electricity", "Fire", "Gauntlet", "Ghosts",
  "Hooks", "Krockheads", "Lights", "Millstones", "Mincers", "Poison",
  "Rising Danger", "Ropes", "Spawners", "Storm", "Tires", "Water", "Wind", "Banana Hoard", "Barn", "Beehive", "Brambles", "Castle", "Caves",
  "Cliffs", "Coral Reef", "Docks", "Factory", "Forest", "Glacier",
  "Gunship", "Ice Cave", "Jungle", "Library", "Mines", "Pipes",
  "Rigging", "River", "Scaffolding", "Ship Deck", "Ship Hold",
  "Swamp", "Temple", "Theme Park", "Trees", "Volcano", "Waterfall"
      ],
    },
  ],
},
  {
  id: '12',
  date: '2024-7-15',
  version: 'v4.3',
  placements: [
    {
      playerId: 'austin',
      teamId: 'team-1',
      characterId: 'kiddy-kong',
      place: 1,
      turnsTaken: 225,
      levelStats: {
        "Jungle Hijinxs": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Ropey Rampage": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Reptile Rumble": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Coral Capers": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Barrel Cannon Canyon": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Very Gnawty's Lair": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Winky's Walkway": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Mine Cart Carnage": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Bouncy Bonanza": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Stop & Go Station": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Millstone Mayhem": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Necky's Nuts": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Vulture Culture": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Tree Top Town": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Forest Frenzy": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Orang-Utan Gang": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Clam City": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Temple Tempest": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Bumble B. Rumble": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Snow Barrel Blast": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Slipslide Ride": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Croctopus Chase": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Ice Age Alley": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Rope Bridge Rumble": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Torchlight Trouble": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Really Gnawty Rampage": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Oil Drum Alley": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Trick Track Trek": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Poison Pond": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Elevator Antics": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Blackout Basement": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Mine Cart Madness": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Boss Dumb Drum": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Tanked Up Trouble": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Manic Mincers": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Misty Mine": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Loopy Lights": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Platform Perils": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Necky's Revenge": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Gang-Plank Galleon": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Pirate Panic": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Mainbrace Mayhem": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Gangplank Galley": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Lockjaw's Locker": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Topsail Trouble": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Krow's Nest": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Hot-Head Hop": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Kannon's Klaim": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Lava Lagoon": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Red-Hot Ride": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Squawks's Shaft": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Kleever's Kiln": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Barrel Bayou": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Glimmer's Galleon": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Krockhead Klamber": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Rattle Battle": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Slime Climb": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Bramble Blast": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Kudgel's Kontest": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Hornet Hole": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Target Terror": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Bramble Scramble": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Rickety Race": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Mudhole Marsh": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Rambi Rumble": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "King Zing Sting": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Ghostly Grove": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Haunted Hall": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Gusty Glade": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Parrot Chute Panic": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Web Woods": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Kreepy Krow": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Arctic Abyss": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Castle Crush": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Clapper's Cavern": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Windy Well": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Chain Link Chamber": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Toxic Tower": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Stronghold Showdown": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Screech's Sprint": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "K. Rool Duel": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Jungle Jinx": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Black Ice Battle": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Klobber Karnage": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Fiery Furnace": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Animal Antics": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Krocodile Kore": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Lakeside Limbo": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Doorstop Dash": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Tidal Trouble": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Skidda's Row": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Murky Mill": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Belcha's Barn": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Springin' Spiders": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Riverside Race": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Squeals on Wheels": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Barrel Shield Bust-Up": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Bobbing Barrel Brawl": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Arich's Ambush": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Bazza's Blockade": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Rocket Barrel Ride": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Kreeping Klasps": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Tracker Barrel Trek": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Fish Food Frenzy": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Squirt's Showdown": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Fire-Ball Frenzy": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Demolition Drain-Pipe": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Ripsaw Rage": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Blazing Bazukas": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Low-G Labyrinth": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "KAOS Karnage": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Krevice Kreepers": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Tearaway Toboggan": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Barrel Drop Bounce": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Krack-Shot Kroc": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Lemguin Lunge": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Bleak's House": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Buzzer Barrage": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Kong-Fused Cliffs": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Floodlit Fish": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Pot Hole Panic": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Ropey Rumpus": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Kroctopus Krush": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Dingy Drain-Pipe": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Stormy Seas": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Sunken Spruce": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Cliffside Blast": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Ripcurl Reef": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Surf's Up": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Barbos's Barrier": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Konveyor Rope Klash": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Creepy Caverns": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Lightning Looks-Out": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Koindozer Klamber": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Poisonous Pipeline": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Kastle KAOS": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Stampede Sprint": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Criss Kross Cliffs": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Tyrant Twin Tussle": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Swoopy Salvo": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Rocket Rush": { buildOrder: 0, star: 0, bang: 0, save: 0 },
  "Knautilus": { buildOrder: 0, star: 0, bang: 0, save: 0 },
      },
      scrapbook: [
        "Clapper", "Ellie", "Enguarde", "Expresso", "Glimmer", "Parry",
  "Quawks", "Rambi", "Rattly", "Squawks", "Squitter", "Winky", "Balloons", "Barrel Cannons", "Barrels", "Boss", "Carts", "Chase",
  "Conveyors", "Doors", "Drums", "Electricity", "Fire", "Gauntlet", "Ghosts",
  "Hooks", "Krockheads", "Lights", "Millstones", "Mincers", "Poison",
  "Rising Danger", "Ropes", "Spawners", "Storm", "Tires", "Water", "Wind", "Banana Hoard", "Barn", "Beehive", "Brambles", "Castle", "Caves",
  "Cliffs", "Coral Reef", "Docks", "Factory", "Forest", "Glacier",
  "Gunship", "Ice Cave", "Jungle", "Library", "Mines", "Pipes",
  "Rigging", "River", "Scaffolding", "Ship Deck", "Ship Hold",
  "Swamp", "Temple", "Theme Park", "Trees", "Volcano", "Waterfall"
      ],
    },
  ],
},

{
  id: 'game1',
  date: '2024-0-15',
  version: 'v5.0',
  placements: [
    {
      playerId: 'austin',
      characterId: 'donkey-kong',
      place: 1,
      turnsTaken: 312,
      levelStats: {
        "Jungle Hijinxs": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Ropey Rampage": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Reptile Rumble": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Coral Capers": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Barrel Cannon Canyon": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Very Gnawty's Lair": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Winky's Walkway": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Mine Cart Carnage": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Bouncy Bonanza": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Stop & Go Station": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Millstone Mayhem": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Necky's Nuts": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Vulture Culture": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Tree Top Town": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Forest Frenzy": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Orang-Utan Gang": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Clam City": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Temple Tempest": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Bumble B. Rumble": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Snow Barrel Blast": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Slipslide Ride": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Croctopus Chase": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Ice Age Alley": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Rope Bridge Rumble": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Torchlight Trouble": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Really Gnawty Rampage": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Oil Drum Alley": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Trick Track Trek": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Poison Pond": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Elevator Antics": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Blackout Basement": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Mine Cart Madness": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Boss Dumb Drum": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Tanked Up Trouble": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Manic Mincers": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Misty Mine": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Loopy Lights": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Platform Perils": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Necky's Revenge": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Gang-Plank Galleon": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Pirate Panic": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Mainbrace Mayhem": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Gangplank Galley": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Lockjaw's Locker": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Topsail Trouble": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Krow's Nest": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Hot-Head Hop": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Kannon's Klaim": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Lava Lagoon": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Red-Hot Ride": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Squawks's Shaft": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Kleever's Kiln": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Barrel Bayou": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Glimmer's Galleon": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Krockhead Klamber": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Rattle Battle": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Slime Climb": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Bramble Blast": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Kudgel's Kontest": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Hornet Hole": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Target Terror": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Bramble Scramble": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Rickety Race": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Mudhole Marsh": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Rambi Rumble": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "King Zing Sting": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Ghostly Grove": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Haunted Hall": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Gusty Glade": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Parrot Chute Panic": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Web Woods": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Kreepy Krow": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Arctic Abyss": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Castle Crush": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Clapper's Cavern": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Windy Well": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Chain Link Chamber": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Toxic Tower": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Stronghold Showdown": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Screech's Sprint": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "K. Rool Duel": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Jungle Jinx": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Black Ice Battle": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Klobber Karnage": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Fiery Furnace": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Animal Antics": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Krocodile Kore": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Lakeside Limbo": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Doorstop Dash": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Tidal Trouble": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Skidda's Row": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Murky Mill": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Belcha's Barn": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Springin' Spiders": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Riverside Race": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Squeals on Wheels": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Barrel Shield Bust-Up": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Bobbing Barrel Brawl": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Arich's Ambush": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Bazza's Blockade": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Rocket Barrel Ride": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Kreeping Klasps": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Tracker Barrel Trek": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Fish Food Frenzy": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Squirt's Showdown": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Fire-Ball Frenzy": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Demolition Drain-Pipe": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Ripsaw Rage": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Blazing Bazukas": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Low-G Labyrinth": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "KAOS Karnage": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Krevice Kreepers": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Tearaway Toboggan": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Barrel Drop Bounce": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Krack-Shot Kroc": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Lemguin Lunge": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Bleak's House": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Buzzer Barrage": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Kong-Fused Cliffs": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Floodlit Fish": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Pot Hole Panic": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Ropey Rumpus": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Kroctopus Krush": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Dingy Drain-Pipe": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Stormy Seas": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Sunken Spruce": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Cliffside Blast": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Ripcurl Reef": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Surf's Up": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Barbos's Barrier": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Konveyor Rope Klash": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Creepy Caverns": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Lightning Looks-Out": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Koindozer Klamber": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Poisonous Pipeline": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Kastle KAOS": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Stampede Sprint": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Criss Kross Cliffs": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Tyrant Twin Tussle": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Swoopy Salvo": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Rocket Rush": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
  "Knautilus": { buildOrder: 0, starOrder: 0, bang: 0, save: 0 },
      },
      scrapbook: [
        'Animal Antics',
        'Rareware Coin',
      ],
    },
  ],
}
]